# Generated by Django 4.1.2 on 2023-01-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cart'),
        ('app', '0037_alter_orden_estatus'),
    ]

    operations = [
    ]
